# Generated by Django 5.1.4 on 2024-12-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Code', models.TextField(max_length=100)),
                ('Linenos', models.BooleanField(default=False)),
                ('Language', models.CharField(max_length=20)),
                ('Style', models.CharField(max_length=20)),
            ],
        ),
    ]
